# TP6

### `Resolver usando Pandas`

Resolver los ejercicios del TP3 utilizando la librer√≠a Pandas.

### Ejercicio 1: Cargar Datos de ventas.

El archivo datos.dat contiene el registro de las ventas realizadas.

Tiene un formato de ancho fijo:
- `fecha`:    10 lugares
- `producto`: 30 lugares
- `precio`:   10 lugares
- `cantidad`:  5 lugares

Hacer una funcion que cargue los datos en un DataFrame de Pandas.

In [21]:
import pandas as pd

def cargar_datos():
    columnas = ["Fecha", "Producto", "Precio", "Cantidad"]
    anchos = [10, 30, 10, 5]
    df = pd.read_fwf('datos.dat', widths=anchos, names=columnas)
    
    return df

datos = cargar_datos()
datos

         Fecha    Producto  Precio  Cantidad
0   2024-08-27     Mirinda    1510        14
1   2024-08-27     Mirinda    1560        12
2   2024-08-28     Torasso     940         8
3   2024-08-29  Pepsi Cola    1210        10
4   2024-08-30     Mirinda    1520         1
5   2024-09-01     Mirinda    1550        15
6   2024-09-01      Sprite     810         4
7   2024-09-02   Coca Cola    1100         4
8   2024-09-02  Pepsi Cola    1220        13
9   2024-09-02     Torasso     910         5
10  2024-09-02     Torasso     920         3
11  2024-09-03   Coca Cola    1020         8
12  2024-09-03     Mirinda    1570         7
13  2024-09-03     Mirinda    1590         2
14  2024-09-04  Pepsi Cola    1220        13
15  2024-09-05     Mirinda    1500         3
16  2024-09-05  Pepsi Cola    1300         5
17  2024-09-06   Coca Cola    1080         1
18  2024-09-06      Sprite     860        12
19  2024-09-06     Torasso     930         3
20  2024-09-07   Coca Cola    1080        14
21  2024-09-07      Sprite     870        13
22  2024-09-08   Coca Cola    1040        10
23  2024-09-08     Mirinda    1580         2
24  2024-09-08  Pepsi Cola    1240         9
25  2024-09-09     Mirinda    1500         3
26  2024-09-09      Sprite     850         9
27  2024-09-10     Mirinda    1590         8
28  2024-09-10  Pepsi Cola    1250        12
29  2024-09-11      Sprite     810         6
30  2024-09-11      Sprite     820        14
31  2024-09-12   Coca Cola    1080         4
32  2024-09-13     Mirinda    1580         5
33  2024-09-13  Pepsi Cola    1250        13
34  2024-09-14   Coca Cola    1080        15
35  2024-09-14  Pepsi Cola    1270        14
36  2024-09-15   Coca Cola    1100         1
37  2024-09-15     Mirinda    1500        13
38  2024-09-15      Sprite     870        14
39  2024-09-15     Torasso     900        13

### Ejercicio 2: Calcular el total de ventas.
Hacer una funci√≥n que sume los importes vendidos (precio * cantidad) y las cantidades.

In [18]:
def calcular_totales(datos):
    importe_total = (datos["Precio"] * datos["Cantidad"]).sum()
    cantidad_total = datos["Cantidad"].sum()
    
    return importe_total, cantidad_total

importe, cantidad = calcular_totales(datos)

print(f"Las ventas fueron de ${importe:.2f} en {cantidad} unidades")

Las ventas fueron de $392730.00 en 335 unidades

### Ejercicio 3: Listar las unidades vendidas.
Listar cu√°ntas unidades se vendieron en total para cada producto

In [27]:
def unidades_vendidas(datos):
    ventas = datos.groupby('Producto')['Cantidad'].sum().reset_index()
    
    return dict(zip(ventas['Producto'], ventas['Cantidad']))

def listar_ventas(ventas):
    for producto, cantidad in ventas.items():
        print(f"Producto: {producto}, Unidades vendidas: {cantidad}")

ventas = unidades_vendidas(datos)
listar_ventas(ventas)

Producto: Coca Cola, Unidades vendidas: 57
Producto: Mirinda, Unidades vendidas: 85
Producto: Pepsi Cola, Unidades vendidas: 89
Producto: Sprite, Unidades vendidas: 72
Producto: Torasso, Unidades vendidas: 32

###  Ejercicio 4: Listar el precio promedio por producto.
Hacer un listado del precio promedio por producto.

In [28]:
def precio_promedio(datos):
    promedio_por_producto = datos.groupby('Producto')['Precio'].mean().reset_index()
    promedio_por_producto.columns = ['Producto', 'Precio Promedio']
    return promedio_por_producto

def listar_precios(datos):
    for index, row in datos.iterrows():
        print(f"El precio promedio de {row['Producto']} es ${row['Precio Promedio']:.2f}")


precios = precio_promedio(datos)
listar_precios(precios)

El precio promedio de Coca Cola es $1072.50
El precio promedio de Mirinda es $1545.83
El precio promedio de Pepsi Cola es $1245.00
El precio promedio de Sprite es $841.43
El precio promedio de Torasso es $920.00

### Ejercicio 5: Ranking de productos
Realizar un listado de los 3 productos m√°s vendidos ordenados por la cantidad de unidades vendidas (ordenadas de mayor a menor)

In [31]:
def ranking_productos(datos, top=3):
    ventas_totales = datos.groupby('Producto')['Cantidad'].sum().reset_index()
    
    ventas_ordenadas = ventas_totales.sort_values(by='Cantidad', ascending=False)
    
    top_ventas = ventas_ordenadas.head(top)
    
    return top_ventas

def listar_ranking(ranking):
    for index, row in ranking.iterrows():
        print(f"Producto: {row['Producto']}, Cantidad vendida: {row['Cantidad']}")
        
ranking = ranking_productos(datos)

listar_ranking(ranking)

Producto: Pepsi Cola, Cantidad vendida: 89
Producto: Mirinda, Cantidad vendida: 85
Producto: Sprite, Cantidad vendida: 72

### Ejercicio 6: Listar las ventas por mes
Realizar un listado del total de unidades vendidas por producto separado por mes.

In [32]:
def ventas_por_mes(datos):
    datos['Fecha'] = pd.to_datetime(datos['Fecha'])
    
    datos['Mes'] = datos['Fecha'].dt.to_period('M')
    
    total_por_mes = datos.groupby(['Mes', 'Producto'])['Cantidad'].sum().unstack(fill_value=0)
    
    return total_por_mes

def listar_ventas_mensuales(ventas):
    for mes, productos in ventas.iterrows():
        print(f"Ventas en {mes}:")
        for producto, total in productos.items():
            print(f"  {producto}: {total} unidades")

ventas = ventas_por_mes(datos)
listar_ventas_mensuales(ventas)

Ventas en 2024-08:
  Coca Cola: 0 unidades
  Mirinda: 27 unidades
  Pepsi Cola: 10 unidades
  Sprite: 0 unidades
  Torasso: 8 unidades
Ventas en 2024-09:
  Coca Cola: 57 unidades
  Mirinda: 58 unidades
  Pepsi Cola: 79 unidades
  Sprite: 72 unidades
  Torasso: 24 unidades

### Ejercicio 7: Informe general

Mostrar un listado de productos ordenados alfabeticamente que contengan el precio promedio, la cantidad de unidades vendidas y el importe total vendido para cada producto

In [33]:
def resumen_ventas(datos):
    datos['Importe'] = datos['Cantidad'] * datos['Precio']

    resumen = datos.groupby('Producto').agg(
        total_cantidad=('Cantidad', 'sum'),
        total_importe=('Importe', 'sum'),
        total_ventas=('Importe', 'count')
    ).reset_index()
    
    resumen['precio_promedio'] = resumen['total_importe'] / resumen['total_cantidad']
    
    return resumen

def informe_ventas(resumen):
    productos_ordenados = resumen.sort_values(by='Producto')

    for _, row in productos_ordenados.iterrows():
        print(f"Producto: {row['Producto']}")
        print(f"  Precio Promedio: {row['precio_promedio']:.2f}")
        print(f"  Total Unidades Vendidas: {row['total_cantidad']}")
        print(f"  Importe Total Vendido: {row['total_importe']:.2f}")
        print()

resumen = resumen_ventas(datos)

informe_ventas(resumen)

Producto: Coca Cola
  Precio Promedio: 1066.32
  Total Unidades Vendidas: 57
  Importe Total Vendido: 60780.00

Producto: Mirinda
  Precio Promedio: 1542.12
  Total Unidades Vendidas: 85
  Importe Total Vendido: 131080.00

Producto: Pepsi Cola
  Precio Promedio: 1241.69
  Total Unidades Vendidas: 89
  Importe Total Vendido: 110510.00

Producto: Sprite
  Precio Promedio: 847.78
  Total Unidades Vendidas: 72
  Importe Total Vendido: 61040.00

Producto: Torasso
  Precio Promedio: 916.25
  Total Unidades Vendidas: 32
  Importe Total Vendido: 29320.00

## `Resolver usando NumPy`
## Resolver el ejercicio 2 del tp1 usando NumPy

### Ejercicio 8

Escribe una funci√≥n en Python que encuentre los valores de `a`, `b`, y `c` para que la funci√≥n cuadr√°tica `f(x) = a x^2 + b x + c` pase exactamente por los siguientes puntos:

| x  | y  |
|---:|---:|
|  0 |  0 |
|  1 |  8 |
|  2 | 12 |
|  3 | 12 |
|  5 |  0 |

### Requisitos:
- La funci√≥n debe explorar posibles valores de `a`, `b`, y `c` utilizando un m√©todo de prueba y error.
- Debe devolver los valores que hagan que la diferencia entre la funci√≥n `f(x)` y los valores medidos `y` sea exactamente cero para cada punto.

> **Pista**: Los valores de `a`, `b`, y `c` son n√∫meros peque√±os.

La idea es implementar el mismo algoritmo que se uso en el TP1 pero usando NumPy en lugar de Python puro.

In [37]:
import numpy as np
def f(x, coeficientes):
    a,b,c = coeficientes
    return a*x**2 + b*x + c

def error(y, y_pred):
    return y - y_pred

X = np.array([0,1,2,3,5])
Y = np.array([0,8,12,12,0])

def buscar_coeficientes():
    A = np.vstack([X**2, X, np.ones(len(X))]).T
    
    coeficientes, residuals, rank, s = np.linalg.lstsq(A, Y, rcond=None)
    
    return coeficientes

coeficientes = buscar_coeficientes()

print(f"Los coeficientes son: a = {coeficientes[0]:.2f}, b = {coeficientes[1]:.2f}, c = {coeficientes[2]:.2f}")

Los coeficientes son: a = -2.00, b = 10.00, c = -0.00

### Ejercicio 9: Resolver el ejercicio 3 del TP1 usando NumPy
Buscar los coeficientes de la funci√≥n que minimice la suma de los cuadrados de las diferencias entre los valores medidos y los valores de la funci√≥n.

1. Crear un array con los coeficientes elegidos al azar (usar `randint(-10,10,3)`).
2. Calcular el valor de la funci√≥n y el error correspondiente.
3. Mientras que el error sea mayor a 1:
    1. Definir nuevos coeficientes agreg√°ndoles un peque√±o valor al azar a los coeficientes actuales (aprendizaje = 0.001).
    2. Si el error para los nuevos coeficientes es menor que el anterior, reemplazar los coeficientes actuales por los nuevos.

In [38]:
import numpy as np
from numpy.random import randint

def f(x, coeficientes):
    a,b,c = coeficientes
    return a*x**2 + b*x + c

def error(y, y_pred):
    return np.sum((y - y_pred)**2)

X = np.array([0, 1, 2, 3, 5])
Y = np.array([0, 8,12,11, 1])

def buscar_coeficientes():
    coeficientes = randint(-10, 10, 3)
    learning_rate = 0.001
    current_error = float('inf')

    y_pred = f(X, coeficientes)
    current_error = error(Y, y_pred)

    while current_error > 1:
        new_coeficientes = coeficientes + np.random.uniform(-learning_rate, learning_rate, 3)
        y_pred_new = f(X, new_coeficientes)
        new_error = error(Y, y_pred_new)

        if new_error < current_error:
            coeficientes = new_coeficientes
            current_error = new_error

    return coeficientes

coeficientes = buscar_coeficientes()

print(f"Los coeficientes encontrados son: a = {coeficientes[0]:.2f}, b = {coeficientes[1]:.2f}, c = {coeficientes[2]:.2f}")

Los coeficientes encontrados son: a = -1.78, b = 8.95, c = 0.62