# TP6

### `Resolver usando Pandas`

Resolver los ejercicios del TP3 utilizando la librer√≠a Pandas.

### Ejercicio 1: Cargar Datos de ventas.

El archivo datos.dat contiene el registro de las ventas realizadas.

Tiene un formato de ancho fijo:
- `fecha`:    10 lugares
- `producto`: 30 lugares
- `precio`:   10 lugares
- `cantidad`:  5 lugares

Hacer una funcion que cargue los datos en un DataFrame de Pandas.

In [3]:
import pandas as pd
def cargar_datos():
    colspecs = [(0, 10), (10, 40), (40, 50), (50, 55)]
    nombresCol = ["fecha", "producto", "precio", "cantidad"]
    df = pd.read_fwf("datos.dat", colspecs=colspecs, header=None, names=nombresCol)
    df['precio'] = pd.to_numeric(df['precio'], errors='coerce')
    df['cantidad'] = pd.to_numeric(df['cantidad'], errors='coerce')
    return df

datos = cargar_datos()
datos

         fecha    producto  precio  cantidad
0   2024-08-27     Mirinda    1510        14
1   2024-08-27     Mirinda    1560        12
2   2024-08-28     Torasso     940         8
3   2024-08-29  Pepsi Cola    1210        10
4   2024-08-30     Mirinda    1520         1
5   2024-09-01     Mirinda    1550        15
6   2024-09-01      Sprite     810         4
7   2024-09-02   Coca Cola    1100         4
8   2024-09-02  Pepsi Cola    1220        13
9   2024-09-02     Torasso     910         5
10  2024-09-02     Torasso     920         3
11  2024-09-03   Coca Cola    1020         8
12  2024-09-03     Mirinda    1570         7
13  2024-09-03     Mirinda    1590         2
14  2024-09-04  Pepsi Cola    1220        13
15  2024-09-05     Mirinda    1500         3
16  2024-09-05  Pepsi Cola    1300         5
17  2024-09-06   Coca Cola    1080         1
18  2024-09-06      Sprite     860        12
19  2024-09-06     Torasso     930         3
20  2024-09-07   Coca Cola    1080        14
21  2024-09-07      Sprite     870        13
22  2024-09-08   Coca Cola    1040        10
23  2024-09-08     Mirinda    1580         2
24  2024-09-08  Pepsi Cola    1240         9
25  2024-09-09     Mirinda    1500         3
26  2024-09-09      Sprite     850         9
27  2024-09-10     Mirinda    1590         8
28  2024-09-10  Pepsi Cola    1250        12
29  2024-09-11      Sprite     810         6
30  2024-09-11      Sprite     820        14
31  2024-09-12   Coca Cola    1080         4
32  2024-09-13     Mirinda    1580         5
33  2024-09-13  Pepsi Cola    1250        13
34  2024-09-14   Coca Cola    1080        15
35  2024-09-14  Pepsi Cola    1270        14
36  2024-09-15   Coca Cola    1100         1
37  2024-09-15     Mirinda    1500        13
38  2024-09-15      Sprite     870        14
39  2024-09-15     Torasso     900        13

### Ejercicio 2: Calcular el total de ventas.
Hacer una funci√≥n que sume los importes vendidos (precio * cantidad) y las cantidades.

In [4]:
def calcular_totales(datos):
    datos['importe'] = datos['precio'] * datos['cantidad']
    total_importe = datos['importe'].sum()
    total_cantidad = datos['cantidad'].sum()
    return total_importe, total_cantidad

importe, cantidad = calcular_totales(datos)

print(f"Las ventas fueron de ${importe:.2f} en {cantidad} unidades")

Las ventas fueron de $392730.00 en 335 unidades

### Ejercicio 3: Listar las unidades vendidas.
Listar cu√°ntas unidades se vendieron en total para cada producto

In [5]:
def unidades_vendidas(datos):
    ventas = datos.groupby('producto')['cantidad'].sum()
    
    for producto, total in ventas.items():
        print(f"Producto: {producto :11} | Unidades Vendidas: {total}")

unidades_vendidas(datos)

Producto: Coca Cola   | Unidades Vendidas: 57
Producto: Mirinda     | Unidades Vendidas: 85
Producto: Pepsi Cola  | Unidades Vendidas: 89
Producto: Sprite      | Unidades Vendidas: 72
Producto: Torasso     | Unidades Vendidas: 32

###  Ejercicio 4: Listar el precio promedio por producto.
Hacer un listado del precio promedio por producto.

In [6]:
def precio_promedio(datos):
    promedio_de_productos = datos.groupby('producto')['precio'].mean()
    for producto, promedio in promedio_de_productos.items():
        print(f"Producto: {producto :11} | Precio Promedio: {promedio:.2f}")

precio_promedio(datos)

Producto: Coca Cola   | Precio Promedio: 1072.50
Producto: Mirinda     | Precio Promedio: 1545.83
Producto: Pepsi Cola  | Precio Promedio: 1245.00
Producto: Sprite      | Precio Promedio: 841.43
Producto: Torasso     | Precio Promedio: 920.00

### Ejercicio 5: Ranking de productos
Realizar un listado de los 3 productos m√°s vendidos ordenados por la cantidad de unidades vendidas (ordenadas de mayor a menor)

In [7]:
def ranking_productos(datos, top=3):
    ventas = datos.groupby('producto')['cantidad'].sum()
    ranking = ventas.sort_values(ascending=False).head(top)
    print(f"Top {top} de los productos vendidos: \n")
    print("----------------------------------------------")
    for producto, cantidad in ranking.items():
        print(f"|Producto: {producto :11} | Cantidad Vendida: {cantidad}|")
    print("----------------------------------------------")

ranking_productos(datos)

Top 3 de los productos vendidos:

----------------------------------------------
|Producto: Pepsi Cola  | Cantidad Vendida: 89|
|Producto: Mirinda     | Cantidad Vendida: 85|
|Producto: Sprite      | Cantidad Vendida: 72|
----------------------------------------------

### Ejercicio 6: Listar las ventas por mes
Realizar un listado del total de unidades vendidas por producto separado por mes.

In [8]:
def ventas_por_mes(datos):
    datos['fecha'] = pd.to_datetime(datos['fecha'], format='%Y-%m-%d')
    datos['mes'] = datos['fecha'].dt.to_period('M')
    ventas_del_mes = datos.groupby(['producto', 'mes'])['cantidad'].sum().reset_index()
    for idx, row in ventas_del_mes.iterrows():
        print(f"Producto: {row['producto'] :11} | Fecha: {row['mes']} | Unidades Vendidas: {row['cantidad']}")

ventas_por_mes(datos)

Producto: Coca Cola   | Fecha: 2024-09 | Unidades Vendidas: 57
Producto: Mirinda     | Fecha: 2024-08 | Unidades Vendidas: 27
Producto: Mirinda     | Fecha: 2024-09 | Unidades Vendidas: 58
Producto: Pepsi Cola  | Fecha: 2024-08 | Unidades Vendidas: 10
Producto: Pepsi Cola  | Fecha: 2024-09 | Unidades Vendidas: 79
Producto: Sprite      | Fecha: 2024-09 | Unidades Vendidas: 72
Producto: Torasso     | Fecha: 2024-08 | Unidades Vendidas: 8
Producto: Torasso     | Fecha: 2024-09 | Unidades Vendidas: 24

### Ejercicio 7: Informe general

Mostrar un listado de productos ordenados alfabeticamente que contengan el precio promedio, la cantidad de unidades vendidas y el importe total vendido para cada producto

In [9]:
def resumen_ventas(datos):
    precio_promedio = datos.groupby("producto")["precio"].mean()
    cantidad_vendida = datos.groupby("producto")["cantidad"].sum()
    datos["importe"] = datos["precio"] * datos["cantidad"]
    total_importe = datos["importe"].sum()
    resumen = pd.DataFrame(
        {
            "precio promedio": precio_promedio,
            "unidades vendidas": cantidad_vendida,
            "total importe": total_importe,
        }
    )
    resumen = resumen.sort_index()
    for producto, row in resumen.iterrows():
        print(f"Producto: {producto :11} | Precio Promedio: {row['precio promedio']:.2f} | Unidades Vendidas: {row['unidades vendidas']} | Importe Total: {row['total importe']:.2f}")


resumen_ventas(datos)

Producto: Coca Cola   | Precio Promedio: 1072.50 | Unidades Vendidas: 57.0 | Importe Total: 392730.00
Producto: Mirinda     | Precio Promedio: 1545.83 | Unidades Vendidas: 85.0 | Importe Total: 392730.00
Producto: Pepsi Cola  | Precio Promedio: 1245.00 | Unidades Vendidas: 89.0 | Importe Total: 392730.00
Producto: Sprite      | Precio Promedio: 841.43 | Unidades Vendidas: 72.0 | Importe Total: 392730.00
Producto: Torasso     | Precio Promedio: 920.00 | Unidades Vendidas: 32.0 | Importe Total: 392730.00

## `Resolver usando NumPy`
## Resolver el ejercicio 2 del tp1 usando NumPy

### Ejercicio 8

Escribe una funci√≥n en Python que encuentre los valores de `a`, `b`, y `c` para que la funci√≥n cuadr√°tica `f(x) = a x^2 + b x + c` pase exactamente por los siguientes puntos:

| x  | y  |
|---:|---:|
|  0 |  0 |
|  1 |  8 |
|  2 | 12 |
|  3 | 12 |
|  5 |  0 |

### Requisitos:
- La funci√≥n debe explorar posibles valores de `a`, `b`, y `c` utilizando un m√©todo de prueba y error.
- Debe devolver los valores que hagan que la diferencia entre la funci√≥n `f(x)` y los valores medidos `y` sea exactamente cero para cada punto.

> **Pista**: Los valores de `a`, `b`, y `c` son n√∫meros peque√±os.

La idea es implementar el mismo algoritmo que se uso en el TP1 pero usando NumPy en lugar de Python puro.

In [10]:
import numpy as np


def f(x, coeficientes):
    a, b, c = coeficientes
    return a * x**2 + b * x + c


def error(y, y_pred):
    return np.mean((y - y_pred) ** 2)


X = np.array([0, 1, 2, 3, 5])
Y = np.array([0, 8, 12, 12, 0])


def buscar_coeficientes():
    posibles_a = np.linspace(-2, 2, 100)
    posibles_b = np.linspace(-2, 2, 100)
    posibles_c = np.linspace(-2, 2, 100)
    min_error = float("inf")
    min_coef = None

    for a in posibles_a:
        for b in posibles_b:
            for c in posibles_c:
                coeficientes = (a, b, c)
                y_pred = f(X, coeficientes)
                err = error(Y, y_pred)

                if err < min_error:
                    min_error = err
                    min_coef = coeficientes
                if min_error == 0:
                    return min_coef
    return min_coef


coeficientes = buscar_coeficientes()
a, b, c = map(float, coeficientes)
print(f"Coeficientes encontrados: a = {a:.4f}, b = {b:.2f}, c = {c:.2f}")

#Este ejercicio fue un dolor de cabeza, y en el output me sal√≠a lo siguiente si no usaba el map:
# (np.float64(-0.3434343434343432), np.float64(2.0), np.float64(2.0))

Coeficientes encontrados: a = -0.3434, b = 2.00, c = 2.00

### Ejercicio 9: Resolver el ejercicio 3 del TP1 usando NumPy
Buscar los coeficientes de la funci√≥n que minimice la suma de los cuadrados de las diferencias entre los valores medidos y los valores de la funci√≥n.

1. Crear un array con los coeficientes elegidos al azar (usar `randint(-10,10,3)`).
2. Calcular el valor de la funci√≥n y el error correspondiente.
3. Mientras que el error sea mayor a 1:
    1. Definir nuevos coeficientes agreg√°ndoles un peque√±o valor al azar a los coeficientes actuales (aprendizaje = 0.001).
    2. Si el error para los nuevos coeficientes es menor que el anterior, reemplazar los coeficientes actuales por los nuevos.

In [11]:
import numpy as np
from numpy.random import randint


def f(x, coeficientes):
    a, b, c = coeficientes
    return a * x**2 + b * x + c


def error(y, y_pred):
    return np.sum((y - y_pred) ** 2)


X = np.array([0, 1, 2, 3, 5])
Y = np.array(
    [0, 8, 12, 11, 1]
)  # Observar que no son los mismos valores que en el ejemplo anterior


def buscar_coeficientes():
    coeficientes = randint(-10, 10, 3)
    err_actural = error(Y, f(X, coeficientes))

    aprendizaje = 0.001
    iteraciones = 0

    while err_actural > 0.001:
        ajuste = np.random.randn(3) * aprendizaje
        nuevo_coef = coeficientes + ajuste
        nuevo_err = error(Y, f(X, nuevo_coef))
        if nuevo_err < err_actural:
            coeficientes = nuevo_coef
            err_actural = nuevo_err
        iteraciones += 1
        if iteraciones > 10000:
            break
    print(f"Numero de iteraciones: {iteraciones}")
    return coeficientes


coeficientes = buscar_coeficientes()
print(
    f"Coeficientes encontrados: a = {coeficientes[0]:.4f}, b = {coeficientes[1]:.4f}, c = {coeficientes[2]:.4f}"
)

# Enserio solo 1 l√≠nea?!

Numero de iteraciones: 10001
Coeficientes encontrados: a = 1.2881, b = -6.6278, c = 8.3082